### ISSUE TITLE
Testing scheme changes using AZwr data.  Unable to load all data.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#100]
Trying to validate the latest WaDE 2.0 schema changes using AZ ground and surface water rights information.  Using both local and QA environment.  Unable to load all data due to unknown reason.  Getting a 'Failure Loading Fact Data' in both cases.

In addition, having some difficulty in translating and understanding the resulting error codes.  May need some assistance from DPL in understanding what the error code mean.

**Test Data (AZwr):** https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Arizona/WaterAllocation/ProcessedInputData/AZwr

**Local Results:**
![image](https://user-images.githubusercontent.com/17555073/101651476-57a57300-39fa-11eb-8ee1-51f67c460cc2.png)

**Local Import Errors:** This error message makes it sound like the exempt rule is not working properly.  In this case (see image) the water right is NOT exempt, and we have flow and a priority date, so this should work.
> [{"Reason":"Allocation Not Exempt of Volume Flow Priority","RowNumber":22276,"OrganizationUUID":"ADWR","VariableSpecificUUID":"ADWR_Allocation All","SiteUUID":"AZwr_S218594","WaterSourceUUID":"AZwr_WS100","MethodUUID":"ADWR_Water Rights SW","BeneficialUseCategory":"STOCK,WILDLIFE","PrimaryUseCategory":"Irrigation","DataPublicationDATE":"2020-12-01","AllocationNativeID":"36-3488.0","AllocationPriorityDate":"1883-12-31","AllocationOwner":"AZ STATE LAND DEPT","AllocationTimeframeStart":"01\/01","AllocationTimeframeEnd":"12\/31","AllocationFlow_CFS":5.540000000000000e+000,"ExemptOfVolumeFlowPriority":false,"OrganizationID":59,"VariableSpecificID":77,"WaterSourceID":745141,"MethodID":98,"PrimaryUseCategoryCV":"Irrigation","CategoryCount":0}

![image](https://user-images.githubusercontent.com/17555073/101653819-fcc14b00-39fc-11eb-8426-d59225823a72.png)

**QA Results:**
![image](https://user-images.githubusercontent.com/17555073/101654250-8a9d3600-39fd-11eb-8f9a-7ef919f7f0e4.png)

**Comment by amabdallah** [comment]
@zlannin  and @Rhipeus  
Here is the logic so we're all on the same page 

If ExemptOfVolumeFlowPriority is True (e.g., for groundwater rights) then allow ALL AllocationFlow_CFS, AllocationVolumn_AF, and AllocationPriorityDate to be null

If ExemptOfVolumeFlowPriority is false (e.g., for surface water rights--majority of data in WaDE) then allow  AllocationFlow_CFS or AllocationVolumn_AF to be null (at least one of them should be provided). AllocationPriorityDate is required, null is not allowed
