### ISSUE TITLE
WaDE Water Right Data Uploader is not accepting / cutting off the amount of sites available to water right.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#106]
Hi DPL.  We are having an issue with our water rights data uploader not accepting / cutting off the amount of sites available to a water right (see image below for example).  Can you guys take a look at this?  Please use this [MT Error Data](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Montana/WaterAllocation/ProcessedInputData/MT_ErrorData) as an example with this issue

As I understand it, it might be an issue with the SiteUUID field having a char length of 250.  Are you able to extend that?  On our end, we can shorten the SiteUUID format we use to identify a state's water right site in our system (thus shortening the field).  But we don't want to change that too much if possible.

![image](https://user-images.githubusercontent.com/17555073/109327112-342ddf80-7815-11eb-94f6-5344dcf0ec38.png)

Thanks.

**Comment by Rhipeus** [comment]
@rwjam - So we were confused by this issue and need to get some clarification.  We thought that the problem was that the SiteUUID field was too long.  However, reading this more carefully, it looks like the issue you are describing is not that the SiteUUID is too short but our loader is not allowing a string long enough for all of the concatenated SiteUUID fields.

I think we got confused because the import already allows up to 1000 characters in that field.  Your example only has about 400 characters.  Is there something we are missing?  Is there a maximum number of characters that you know we should handle?  Do you have an example field that is more than 1000 characters?

**Comment by amabdallah** [comment]
@Rhipeus so the question here then is why these 400 characters are not loading then if the data loader allows up to 1,000? we'll look more into the issue and get back to you.

**Comment by Rhipeus** [comment]
Any updates on this?  Is there anyway that we can provide any assistance here?

**Comment by rwjam** [comment]
@Rhipeus.  Try this.  I had to create an sample data to recreate this error.  This is an example of a single water right having many sites.

Can you please try pushing this **ID_Error** data to the QA and let us know the results please?
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Idaho/WaterAllocation/ProcessedInputData/IDwr_error

**Comment by RyanMcManaman** [comment]
@rwjam I've upped the size of the SiteUUID column to its maximum, and the change is currently being reviewed in PR. Your example data will now succeed in importing given that you fix the following issues:

- [Variables.csv] `AggregationIntervalUnitCV` value 'Year' not present in `CVs.Units`, changed to 'AF' to pass import
- [Variables.csv] `MaximumAmountUnitCV` value 'AFY' not present in `CVs.Units`, changed to 'AF' to pass import
- [Variables.csv] `VariableSpecificCV` value 'Allocation All' not present in `CVs.VariableSpecific`, changed to 'AF' to pass import
- [Sites.csv] EPSG code needs to match "Name" value in `CVs.EPSGCode`, not "Term". Additonally, the "Term" value in the original file contained an erroneous colon. 

All of these are based on current values from your CV API. If you'd like to use terms like "Year" or "AFY", they need to be added to the CV API before the importer will be able to recognize them. I ran the import on a fresh database/repo yesterday and didn't see them in the returned data.

Attached is a ZIP containing the amended CSV files. Please let me know if you have any questions!

[IDwr_error.zip](https://github.com/WSWCWaterDataExchange/WaDE2.0/files/6345780/IDwr_error.zip)
