### ISSUE TITLE
WaDE Data Uploader / Database not accepting 1-to-many relationship with either RegulatoryOverlayUUIDs or WaterSourceUUID field in the Sites_dim Table.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#127]
**Describe the bug**
Issue with the data uploader **LoadSitesBatch** function not accepting a 1-to-many relationship / csv entry in the uploading sites.csv flies in either of both the **RegulatoryOverlayUUIDs** & **WaterSourceUUID** fields.

![image](https://user-images.githubusercontent.com/17555073/129636996-22ab8c85-3c5c-44bf-ade5-c72ba23c45da.png)
 
![image](https://user-images.githubusercontent.com/17555073/129636826-56ed363e-f87a-4fbe-afa2-394bc6c1a886.png)

These fields need to behave similarly to the **BeneficialUse** or **SiteUUID** entries in the waterallocaitons.csv input when we work with water allocation data.

![image](https://user-images.githubusercontent.com/17555073/129637184-3edc338f-a02d-472c-8998-16ef7fd340bc.png)

![image](https://user-images.githubusercontent.com/17555073/129637376-a5607dee-d3c6-4c5f-9375-8b06de9f914d.png)

**To Reproduce**
- Will create reproducible input data upon request at a later date. 
-  Issue first appeared with CA ss data, and NM re data.

**Comment by Rhipeus** [comment]
Currently, the sites.csv file does accept multiple Regulatory Overlays and will load the records necessary from a comma-delimited list.

The relationship between sites.csv and water sources today is each site has a unique water source.  Today, there is not a need for a site having multiple water sources.  The ability to have multiple water sources for a single site is a new feature in active development.

Looking at the error, the most likely cause for that error is the sites.cvs import file duplicated the "NMwr_S1" key within the file.

**Comment by rwjam** [comment]
Been resolved.
