### ISSUE TITLE
WaDE Schema Update - Missing connection between Core.RegulatoryOverlay_dim & Cv.RegulatoryStatusCV tables.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#128]
Noticed the RegulatoryStatusCV table was not updating correctly.  Looks like Core.RegulatoryOverlay_dim table in the QA has no key to the Cv.RegulatoryStatusCV table.

![image](https://user-images.githubusercontent.com/17555073/135343099-a5fedbb6-3f67-48bb-a91a-2b1842c12046.png)

**Comment by Rhipeus** [comment]
The missing index can be added as a data integrity check.

However, that would not cause any problems with loading RegulatoryStatusCV table, which sounds like your real issue.  The only way that table gets populated is via a nightly process that pulls data from the CV API, which is currently down and would be why it isn't updating.

Or did you mean that the RegulatoryStatusCV _column_ on the RegulatoryOverlays table is not being loaded?  If so, I've run some tests and am not seeing that issue.  I'd need more information to recreate the problem.

**Comment by rwjam** [comment]
Been solved.
