### ISSUE TITLE
Texas ss WaDE data uploader cutting off at 2,500 mark for unknown reason when using LoadSiteSpecificAmounts function.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#151]
We are having an issue with the WaDE data uploader not fully uploading all site specific amount records, specifically for the latest Texas data.  The uploader seems to be cutting out / stopping at the 25,000 mark (where in reality we have about 2,523,652 records we wanted to push).

Not fully sure if this is either a A) WaDE data uploader, or B) an issue with the data we are trying to push.  Could use a second opinion to help determine what is causing the problem.

See error...
- Date (UTC): 2022-05-04 21:37:12.571
- Operation ID: 989c62b993701d1bce6930755c6e214d

Here is a link to the TX ss data we tried to upload to the QA:
- https://drive.google.com/drive/folders/1FjmKoyxFv8Wctfmzx4NDTbvOqq8cgSAt?usp=sharing

![image](https://user-images.githubusercontent.com/17555073/166831772-ec6e3375-88d3-4754-8a69-6269f0c03ca3.png)

**Comment by rwjam** [comment]
We are actually having a similar issue here
- https://github.com/WSWCWaterDataExchange/WaDE2.0/issues/143

**Comment by amabdallah** [comment]
@rwjam does this issue still exist? If so, let's discuss

**Comment by rwjam** [comment]
It does not, let's close it.
