### ISSUE TITLE
Why is the geometry field in either the Core.Sites_dim or Core.ReportingUnit_dim encrypted?

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#169]
Why is the geometry field in either the Core.Sites_dim or Core.ReportingUnit_dim encrypted?  In it's current state, who is benefiting have the data like this?  This is more relevant for the use of POU polygons for water right and site specific data, and reporting unit areas for aggregated data.

From our perspective and use, this should return as [WKT format](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry) so we are not reliant on trying to pair shapefile data to WaDE data after it's been upload.

![image](https://user-images.githubusercontent.com/17555073/197815304-e7d29985-e898-4d79-ae54-e04d7418ca18.png)

**Comment by bbarber** [comment]
@rwjam - I may be misunderstanding, but could you query the table with the using `.STAsText()` to view the WKT format of the geometry? By default it will display the WKB (well-known binary) format. Unless this column is truely encrypted (which I'm not aware of if it is or isn't)

The syntax would be something like `select Geometry.STAsText() from Core.Sites_dim` or similar

**Comment by rwjam** [comment]
@bbarber - I was not aware of that.  I've always been working under the assumption that the geometry was being encrypted for some reason.

That `.STAsText()` to view the WKT format worked great for my purposes.  Thank you for shareing that with me.
