### ISSUE TITLE
WaDE Bug - unable to upload any provided url into WaterAllocationNativeURL field.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#172]
We are having trouble getting any provided url string into our WaterAllocationNativeURL field in the Core.AllocationAmounts_fact table.  We are unsure why this is occurring.  We are not getting any error message for this either.

Here is an example of a NM provided url string: http://nmwrrs.ose.state.nm.us/ReportDispatcher?type=WRHTML&name=WaterRightSummaryHTML.jrxml&basin=G&nbr=01904&suffix=

Here is an example of a NV provided url string: http://water.nv.gov/permitinformation.aspx?app=1

**Comment by rwjam** [comment]
2023-03-16.

We would like to re-use our WaDE QA data uploader.  However, we are unsure how up-to-date it is, as it has been some time since we last used it.  Here is an example of our latest findings on errors.


- Here is the link to the QA data uploader monitor where you can view errors on the Invocations tap ([link](https://portal.azure.com/#view/WebsitesExtension/FunctionMenuBlade/~/monitor/resourceId/%2Fsubscriptions%2F7847533a-6a20-4b25-a2b5-f50e005985c5%2FresourceGroups%2FWaDE_QA%2Fproviders%2FMicrosoft.Web%2Fsites%2FWaDEImportFunctions-QA%2Ffunctions%2FLoadWaterAllocationDataOrchestration)) .  You can see in the last few errors we are experiencing ‘CVs.WaterQualityIndicator’ issue, which tells me the uploader is having an issue with matching CV terms to the uploaded data.
- Here is a link to a subset of ID data I tried using ([link](https://portal.azure.com/#@WaDEWSWChotmail.onmicrosoft.com/resource/subscriptions/7847533a-6a20-4b25-a2b5-f50e005985c5/resourceGroups/WaDE_QA/providers/Microsoft.Storage/storageAccounts/wade2stoageqa/storagebrowser)).  In the ‘WaterQualityIndicatorCV´field within the watersource.csv we have a value of Unspecified.
- Here’s a link to the QA database query editor where we can see what elements are in the CV.WaterQualityIndicator table ([link](https://portal.azure.com/#@WaDEWSWChotmail.onmicrosoft.com/resource/subscriptions/7847533a-6a20-4b25-a2b5-f50e005985c5/resourceGroups/WaDE_QA/providers/Microsoft.Sql/servers/wade-qa-server/databases/WaDE_QA/queryEditor)).  There should already b a value of Unspecified in there.
- `SELECT * FROM [CVs].[WaterQualityIndicator]`

![image](https://user-images.githubusercontent.com/17555073/225703529-6469c91b-d5d9-493a-aa0a-e050248b5dfc.png)

**Comment by amabdallah** [comment]
Hi @aneilsen 

Would you please check why the data uploader is failing? It does appear to be related to the WaterSources_dim table and specificity to the CVs.WaterQualityIndicator. It's not making sense to us why this error is happening.

>  The MERGE statement conflicted with the FOREIGN KEY constraint "fk_WaterSources_dim_WaterQualityIndicator". The conflict occurred in database "WaDE_QA_Server", table "CVs.WaterQualityIndicator", column 'Name'. The statement has been terminated.

The sample data that Ryan is using exist here
wade2storageqa -> Blob Containers -> normalizedimports -> IDwr

**Comment by amabdallah** [comment]
This could be relevant 
https://github.com/WSWCWaterDataExchange/WestDAAT-infrastructure/blob/main/Steps_Upload_Data_to_db.md

**Comment by amabdallah** [comment]
This problem does not exist in Staging. So I'm closing it.
