### ISSUE TITLE
Add new field to the Methods table: WaDEDataMappingURL

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WaDE2.0#180]
**Need**
To be transparent, we need to provide a URL to how state data was mapped into WaDE with all the assumptions etc. This page exists on GitHub under a ReadME for each data type, such as [here ](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/California/WaterAllocation)

**Problem**
The current field in the database for this URL exists in the Organisations table [here](https://schema.westernstateswater.org/columns/Core_Organizations_dim_OrganizationDataMappingURL.html) but each organization may provide multiple datasets

**Suggested Solution**
I think it would be best if we moved the "OrganizationDataMappingURL" into the Methods table and renamed it to something like "WaDEDataMappingURL". It could be easier to just create a new filed in the Methods table 
https://schema.westernstateswater.org/tables/Core_Methods_dim.html

This new WaDEDataMappingURL should be accessible on each WestDAAT landing page under the Methods Card under a label called: **WaDE Data Mapping Process**

https://westdaatstaging.westernstateswater.org/details/right/COwr_WR139596?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABhNSSwFcAJshgBmfADo2ANikB2WVPxLlSqdxoA7AOb8hMbJwAc4jgCY2AFkOmVKgL52gA

**Comment by amabdallah** [comment]
This is how it would look like 

![image](https://github.com/WSWCWaterDataExchange/WaDE2.0/assets/3268971/154d7c5b-f333-4b5d-a561-e78b29f476b0)

**Comment by rwjam** [comment]
Seems like this change has led to a small bug.

The WaDE Uploader is expecting a "WaDEDataMappingUrl' input, but the WaDE database is displaying a "WaDEDataMappingURL" value (note the difference in case with the URL portion)

**Comment by amabdallah** [comment]
@Andrew-L-Campbell 
Here is a potential bug fix you could look into. Let's first meet together with @rwjam to discuss this. 
You can see here where the code has lowercase and uppercase discrepancies.  
https://github.com/search?q=repo%3AWSWCWaterDataExchange%2FWaDE2.0%20WaDEDataMappingUrl&type=code
