### ISSUE TITLE
Core.ImportErrors taking too long to display contents

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/WaDE2.0#67]
Trying to inspect import errors in WaDE QA DB (in SQL Server MS) takes too long (> 9 min) to show its contents. There are about 20 rows in the table "Core.ImportErrors", yet other tables (e.g., AllocationAmounts_fact) that have >400K rows take much shorter time to display their contents.

SQL script used: 

SELECT *
  FROM [Core].[ImportErrors]

**Comment by Rhipeus** [comment]
There really isn't a way to make a `Select * from X` type query faster.  There are no indexes at play.  It is always going to take the time that it takes.

The purpose of ImportErrors is to give us some insight into why things are failing.  To that end, you are probably only interested in the last few sets of import errors.  Thus, you have a couple of options:

1) You can delete the old records
2) `Select Top(5) * from X order by id desc`

I would actually recommend a combination of both.

**Comment by tsga** [comment]
OK. Thank you..
