### ISSUE TITLE
WaDECV trigger not updating StateCV

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/WaDE2.0#69]
The new entrees for StateCV in the Controlled vocabulary website are not being updated in the QA DB even after calling the WaDECV update trigger in the Azure portal.

This was noticed while working to update the StateCV related to water rights data of WA, OR, ND (It is likely true to other states).

**Comment by amabdallah** [comment]
I'm not sure what the exact issue was here but it seems we're facing a similar one now.

This table has new entries. See State value: NE (it does exist) 
http://vocabulary.westernstateswater.org/beneficialusecategory/

But the database does not have any value for State=NE (see the SQL below)

We looked at the AutoUpdateCvData in Azure and it seems to run "successfully". So we're not sure why those values are not loading to the db.

```
SELECT TOP (1000) [Name]
      ,[Term]
      ,[Definition]
      ,[State]
      ,[SourceVocabularyURI]
      ,[USGSCategory]
      ,[NAICSCode]
  FROM [CVs].[BeneficialUses]

  where state like '%NE'
```

**Comment by amabdallah** [comment]
Nathan responded in email saying this:

> Looking at the logs*, it looks like there are at least two records with issues and they both have the same basic problem, data that is too long for the DB coming from the CV data.
> 
> BeneficialUses
> There is at least one name field that is too long “Storage Use-only for irrigation from reservoir on lands not covered by natural flow appropriation AN".  There is more to that string but it is too long for the DB at more than 100 characters.  This is an easy change if we need to support more than 100 characters.
> 
>  WaterAllocationBasis
> This is the same or similar to what we discussed several months ago where “Unknown” has a state field with multiple states in it.  Again, it comes down to a truncation problem where the expectation is a single state.  This is a far more involved change if we need to support multiple states per CV record.


For now, we'll extend those fields manually and add them to the list of minor changes we need help with later.

**Comment by amabdallah** [comment]
We're expanding the "State" column in the CV tables to be 250 nvarchar to allow storing comma seperated state values.
