### ISSUE TITLE
Minor schema updates 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WaDE2.0#83]
The following schema updates are for new field additions or updates. 

**Core.Organization table**
Rename State to StateCV

**Core.Site table**
* CoordinateAccuracy: update the length to 250 instead of 255, for consistency 
* Add a new field called: PODorPOUSite [optional and takes Nvarchar 50
* Make longitude and latitude as required fields (no null allowed)
* Change SiteUUID length to 500

**Add new CV tables**
PowerTypeCV [a copy of the crop type CV table] . 
LivestockSpecies [a copy of the crop type CV table] 

**In all CV tables**
We need to extend the "state" field to be 100 char to support having many comma-separated values there.
We also want to extend the "name" field to be 150 char to support values that are up to that long.

**WaterSources_dim**
* Change WaterSourceUUID length to 500

**CVs.BeneficialUseCV**
1. Update these two columns: USGSCategory and NAICSCode into USGSCategoryCV and NAICSCodeCV in the BeneficialUseCV table? so just add CV at the end.
2. Add a new field optional called: WaDEBeneficialUse with a 255 NvarChar length. 

**Core.AllocationAmounts_fact**
Update the field names:
* AllocationAmount to AllocationFlow_CFS
* AllocationMaximum to AllocationVolume_AF
* Make the AllocationOwner length to be 500 Nvarchar

* Add these new fields:
-- LivestockServed [Optional and takes float]
-- LivestockSpecies [Optional and takes values from the CV table]
-- ExemptOfVolumeFlowPriority [Optional and takes Boolean values, yes or no]
-- PowerTypeCV 

If the value is yes, then AllocationFlow, AllocationMaxVolume, and AllocationPriorityDate, all can be null 
So AllocationPriorityDate should be allowed to be null. The data loader should implement business logic to enforce AllocationPriorityDate being required if  ExemptOfAmountLimit value is "no"

**Core.AggregateAmounts_fact** 
Add these new fields:
LivestockServed [Optional and takes float]. 
LivestockSpecies [Optional and takes float]. 
PowerTypeCV 
Update ReportingUnitID to ReportingAreaID (see the related change below)

**Core.SiteVariableAmounts_fact** 
Add these new fields:
LivestockServed [Optional and takes float]. 
LivestockSpecies [Optional and takes float]. 
PowerTypeCV [Optional]. 

This is a new category in the metadata groups that the data loader checks on to validate no metadata mixing among these groups
Group A: PopulationServed, SDWISIdentifierCV, CustomerTypeCV, CommunityWaterSupplySystem
Group B: IrrigatedAcreage, CropTypeCV, IrrigationMethodCV
Group C: PowerGeneratedGWh, PowerType
_Group D: LivestockServed, LivestockSpecies 

**Core.ReportingUnit_dim**
Change ReportingUnit_dim table and its rows into use Area instead of Unit

ReportingUnit_dim to ReportingArea_dim 
ReportingUnitID to ReportingAreaID 
ReportingUnitUUID to ReportingAreaUUID 
ReportingUnitNativeID to ReportingAreaNativeID
ReportingUnitName to ReportingAreaName
ReportingUnitTypeCV to ReportingAreaTypeCV
ReportingUnitUpdateDate to ReportingAreaUpdateDate
ReportingUnitProductVersion to ReportingAreaProductVersion

**Core.Variables_dim**
Update AmountUnitCV to UnitCV
Delete MaximumAmountUnitCV 
Add a new field called: 
NoDataValue [optional and has Nvarchar of 20]
[This field defines a value in case null is provided.  
](https://github.com/ODM2/ODM2/blob/6da9d708d0f208541d497a2582d5dd83683401a3/doc/ODM2Docs/core_variables.md#no-data-values)

**Data Loader**
If the provided value of the (AllocationAmount, now AllocationFlow) or (AllocationMaximum, now AllocationVolume) are null, then we need update value to -9999

**Core.RegulatoryReportingUnits_fact**
Update table name from RegulatoryReportingUnitsExemptOfVolumeFlowPriority_fact to RegulatoryReportingAreas_fact
Update ReportingUnitID tp ReportingAreaID (see the related change below)

**New field length across all tables** 
LivestockServed [float]
LivestockSpecies [50]
PowerType [50]

**Question**
Should the ReportYearCV field in the amount tables be required? its optional now

**Comment by amabdallah** [comment]
In all the CV tables, make the State column length to 250 char. We will be storing all states that share the same term.

Also, add a new column in all the CV tables. The column names start with WaDE and then takes the table name. 
e.g., BeneficialUseCategory

**Comment by amabdallah** [comment]
@rwjam when you work on the regulatory data such as these two below, would you see which new metadata fields we should add? 
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/51 and https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/49, 
Here is a couple to start thinking about to help users filter the western us map with lots of regulatory overlays. 
**RegulatoryOverlayTypeCV**:  e.g., Compact, Districts, Special Statutory Area (not sure what to call this one but examples are like AMA in Arizona and SGMA Groundwater Management in California).

**RegulatoryBoundaryTypeCV**: e.g., Political (such as conservancy or district), Watershed, Groundwater Basin,   

**Others?**

The point of adding such metadata is to allow users to filter and query data to answer questions of interest.

**Comment by rwjam** [comment]
As a whole, I think we may need to be slack in our data requirements with the regulatory data into WaDE 2.0.  Some of the requested regulatory polygons are not similar in the type of information they provide (meaning trying to combing them all into one schema may be difficult).

For example, see AZ reg data requests: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/49

1. AZ AMA are state defined governor appointed councils who's goal are to maintain a state defined 'safe-yield' conditions and prevent local water tables from being expended (these are more heavily based on law and rules).
2. AZ Irrigation Districts are political subdivision and municipal corporation of the State of Arizona who have a broad range of powers and purposes which include the ability to purchase or acquire water rights, own or sell property and real estate, construct facilities, generate electricity, appropriate water for irrigation and power generation, tax and charge for services, appropriate money, and provide the district with water, electricity, and other public conveniences and necessities generally provided by municipalities.

**Comment by amabdallah** [comment]
Eventually, we want to filter spatial polygons (layers) for regulatory overlays based on a common theme that satisfies a user case. For example, show me all the compacts in the west, show me all the groundwater-related regulations in the west (e.g., CA SGMA, AZ AMA)


Here is a couple to start thinking about to help users filter the western us map with lots of regulatory overlays.
RegulatoryOverlayTypeCV: e.g., Compact, Districts, Special Statutory Area (not sure what to call this one but examples are like AMA in Arizona and SGMA Groundwater Management in California).

RegulatoryBoundaryTypeCV: e.g., Political (such as conservancy or district), Watershed, Groundwater Basin,

Others?

**Comment by rwjam** [comment]
Issue of trying to upload and update BeneficialUseCVs and the BenUseBridge tables.  Won't update if the 'PrimaryBeneficialUse" field is left empty when uploading data.  The PrimaryBeneficialUse is meant to be option and help with visualizations. 

I'd say we could either a) remove PrimaryBeneficialUse field, or b) remove this requirement to update the bridge tables.
