### ISSUE TITLE
Data Loader issue with either a AllocationFlow_CFS or a AllocationVolume_AF (ie., we needed one or the other).

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#96]
Ran into a bug using some Montana POD water rights data in the situation where the water right DID have a AllocationVolume_AF value, but DID NOT have a AllocationFlow_CFS, but the code still caused an error with the missing AllocationFlow_CFS.

Ideally we should have one or the other, even if one value is NULL.  For example...
- Okay: AllocationFlow_CFS = NULL & AllocationVolume_AF = 5
- Okay: AllocationFlow_CFS = 5 & AllocationVolume_AF = NULL
- Okay: AllocationFlow_CFS = 5 & AllocationVolume_AF = 0
- Okay: AllocationFlow_CFS = 0 & AllocationVolume_AF = 0
- Bad: AllocationFlow_CFS = NULL & AllocationVolume_AF = NULL

Data used: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Montana/WaterAllocation/ProcessedInputData/MTwr

**Comment by Rhipeus** [comment]
This change has been deployed to the QA environment.  Give it another try and let us know how it goes.

**Comment by rwjam** [comment]
Didn't seem to work.  I'm afraid I'm getting new errors now (see image below).  I've tried removing all exiting MT data previously loaded, but that didn't seem to work.

![image](https://user-images.githubusercontent.com/17555073/101187079-20f1e600-3611-11eb-89ed-f14c9e4635b6.png)

**Comment by zlannin** [comment]
Try pulling latest develop branch and re-running.

**Comment by rwjam** [comment]
Pulled from develop branch and re ran.  Didn't seem to work.  Tried on both local and QA.

Local
![image](https://user-images.githubusercontent.com/17555073/101209486-092a5a00-3631-11eb-802e-dabf60dd1deb.png)

QA
![image](https://user-images.githubusercontent.com/17555073/101212681-607ef900-3636-11eb-9045-9908033de55b.png)

**Comment by zlannin** [comment]
For QA, double check your water allocation data, specifically "WaterRightsType" column. It looks like there's a value in that column that doesn't exist in CVs.WaterAllocationType.

**Comment by zlannin** [comment]
For local, that error generally indicates the Stored Procedure was not successful. Please look at your Core.ImportErrors table for why the stored procedure failed.

**Comment by rwjam** [comment]
In a weird spot.  

I was able to upload data to QA **successfully**.  For QA, I was able to double check the "WaterRightsType" column in the water allocation data and fine the value in that column that didn't exist in CVs.WaterAllocationType.

However, I am **unable** to make the local work still.  The error in the Core.ImportErrors table relates to the missing AllocationFlow_CFS value, but we have a AllocationVolume_AFvalue.  So this should load here.

Core.ImporteErrors:

> [{"Reason":"Allocation Not Exempt of Volume Flow Priority","RowNumber":1,"OrganizationUUID":"MDNRC","VariableSpecificUUID":"MT_Consumptive Use","SiteUUID":"MTwr_S1","WaterSourceUUID":"MTwr_WS1","MethodUUID":"MT_Water Allocation App","BeneficialUseCategory":"STOCK","PrimaryUseCategory":"Irrigation","DataPublicationDATE":"2020-11-20","DataPublicationDOI":"http:\/\/wr.dnrc.mt.gov\/reports\/rwservlet?dnrcwr&report=WRD2090AR.rep&P_WRGT_ID_SEQ=180441","AllocationNativeID":"38H 102244 00","AllocationPriorityDate":"1997-11-25","AllocationOwner":"USA (DEPT OF INTERIOR BUREAU OF LAND MGMT)","AllocationBasisCV":"Unknown","AllocationLegalStatusCV":"ACTIVE","AllocationTypeCV":"STOCKWATER PERMIT","AllocationTimeframeStart":"01\/1","AllocationTimeframeEnd":"12\/31","AllocationVolume_AF":5.400000000000000e+000,"ExemptOfVolumeFlowPriority":false,"OrganizationID":58,"VariableSpecificID":118,"WaterSourceID":687403,"MethodID":96,"PrimaryUseCategoryCV":"Irrigation","CategoryCount":0},

![image](https://user-images.githubusercontent.com/17555073/101523244-93323580-3945-11eb-81f3-6ea493bb1a6f.png)

![image](https://user-images.githubusercontent.com/17555073/101522995-39ca0680-3945-11eb-83ea-2d39b6d1cd0d.png)

**Comment by zlannin** [comment]
Are we good to close this issue?

**Comment by rwjam** [comment]
yes


*Ryan James - Data Analyst / Hydroinformatics Specialist*
*Western States Water Council, UT*
*(801) 685-2555*
